apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-clustersecretrstore-sm
spec:
  provider:
    aws:
      service: SecretsManager
      role: arn:aws:iam::398767507008:role/external-secrets-platform-IRSA20230831144720029800000002
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets