apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data-pv
  namespace: jenkins
spec:
  capacity:
    storage: 8Gi  
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0fe51df3cfe28938f  # Replace with your EBS volume ID
  
