# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: test
spec:
  replicas: 2  # Adjust as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      restartPolicy: Always
      containers:
        - name: my-app-container
          image: 398767507008.dkr.ecr.us-east-1.amazonaws.com/apiapp:1.6
          ports:
          - containerPort: 80
